version: "3.8"

services:
  kafka1:
    image: docker.io/bitnami/kafka:3.3
    container_name: ${KAFKA_CONTAINER_NAME_1}
    hostname: ${KAFKA_HOST_1}
    ports:
      - "29092:9092"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@${KAFKA_HOST_1}:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://${KAFKA_HOST_1}:9092
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true 

  kafka2:
    image: docker.io/bitnami/kafka:3.3
    container_name: ${KAFKA_CONTAINER_NAME_2}
    hostname: ${KAFKA_HOST_2}
    ports:
      - "29093:9092"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_BROKER_ID=2
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://${KAFKA_HOST_2}:9092
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true 

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    container_name: ${SCHEMA_REG_CONTAINER_NAME}
    hostname: ${SCHEMA_REG_HOST}
    depends_on:
      - kafka1
      - kafka2
    environment:
      - SCHEMA_REGISTRY_HOST_NAME=${SCHEMA_REG_HOST} 
      - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=${KAFKA_HOST_1}:9092,${KAFKA_HOST_2}:9092
      - SCHEMA_REGISTRY_LISTENERS=http://${SCHEMA_REG_HOST}:8081
    ports:
      - "8081:8081"

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.0
    container_name: dataeng-kafka-ui
    depends_on:
      - kafka1
      - kafka2
      - ksqldb
      - schema-registry
    ports:
      - "8083:8080"
    restart: "no"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=${KAFKA_HOST_1}:9092,${KAFKA_HOST_2}:9092
      - KAFKA_CLUSTERS_0_KSQLDBSERVER=http://${KSQL_HOST}:8088
      - KAFKA_CLUSTERS_0_SCHEMAREGISTRY=http://${SCHEMA_REG_HOST}:8081

  ksqldb:
    image: bitnami/ksql:7.4
    container_name: ${KSQL_CONTAINER_NAME}
    hostname: ${KSQL_HOST}
    depends_on:
      - kafka1
      - kafka2
      - schema-registry
    ports:
      - "8088:8088"
    environment:
      - KSQL_BOOTSTRAP_SERVERS=${KAFKA_HOST_1}:9092,${KAFKA_HOST_2}:9092
      - KSQL_CLIENT_AUTHENTICATION=none
      - KSQL_SCHEMA_REGISTRY_URL=http://${SCHEMA_REG_HOST}:8081

networks:
  default:
    name: dataeng-network
    external: true
